### ISSUE TITLE
May be we should add ability to pass connection string via ENV or with file name of secret. 

### ISSUE THREAD

**Issue by holyslon** [dodopizza/aspnet-session-cosmosdb#3]
May be we should add ability to pass connection string via ENV or with file name of secret. 
This might be useful when you don`t want store connection string inside your git repository together with configs.
https://github.com/dodopizza/aspnet-session-cosmosdb/blob/882b51b14ebcfdec003aeb139eb6d0b50be8194e/Dodo.AspNet.SessionProviders.CosmosDb/CosmosDbSessionStateProvider.cs#L56

**Comment by george-polevoy** [comment]
I think it should be a client responsibility to modify the config with Transform.
Another possibility (currently used in our own prod application) is to wrap provider and parse config from other sources.

I see no strong reason for cluttering the implementation with any possible combination of environmental acquisition for config.
In fact, a possibility to specify a connection string using env vars was implemented earlier, but then removed for good.

https://github.com/dodopizza/aspnet-session-cosmosdb/commit/8f1af6dc838af1f2589ddcf7a7815177d6ef8143#diff-e014aa90647394301a4a10249b9285533fa76012ecd871de24cbe72888170869L73
